version: "0.1" 
services:
  mysql: 
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=database_development"
      - "MYSQL_DATABASE=database_test"
      - "TZ=Asia/Shanghai"
    ports: 
      - 3306:3306
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${hostIP}
      KAFKA_ZOOKEEPER_CONNECT: ${hostIP}:2181
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"